language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Shashkin_All_projects
  - make -j
  - cd ./Vector
  - ./VectorTest/All_projects
notifications:
  email: false
